name: Checking Master Branch
on:
  push:
    branches:
      - master
jobs:
  check_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build package
      run: |
        make build
